version: "3.7"

services:
  logspout:
    image: gliderlabs/logspout
    networks:
      - logs
    command: syslog+tls://logs.papertrailapp.com:$PAPERTRAILPORT
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ALLOW_TTY=true

networks:
  logs: 
